name: IPTV Update

on:
  schedule:
    - cron: "0 0 * * *"   # 每天运行一次
  workflow_dispatch:

jobs:
  update-iptv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download remote txt
        run: |
          curl -sL "https://raw.githubusercontent.com/redrainl/iptv/main/speedtest/txt/fofa_Shanghai_103.txt" -o raw.txt

      - name: Filter channels (CCTV + 卫视)
        run: |
          # 保留 CCTV 和 卫视，并去掉坏链接 http:///
          grep -E 'CCTV|卫视' raw.txt | grep -v 'http:///' | sort -u > filtered.txt

          # --- CCTV 排序 (提取数字并排序 1-17) ---
          grep 'CCTV' filtered.txt | \
            sed -E 's/^CCTV-?([0-9]+)/CCTV\1/' | \
            awk -F, '{
              if (match($1,"CCTV[0-9]+")) {
                num = substr($1, RSTART+4, RLENGTH-4);
                print $0","num
              }
            }' | sort -t, -k3,3n | cut -d, -f1,2 > cctv_sorted.txt

          # --- 卫视排序 (按拼音) ---
          grep '卫视' filtered.txt | LC_ALL=C sort -t, -k1,1 > weishi_sorted.txt

          # --- 合并 ---
          cat cctv_sorted.txt weishi_sorted.txt > clean.txt

      - name: Convert local iptv.txt to m3u
        run: |
          if [ -f iptv.txt ]; then
            echo "#EXTM3U" > local.m3u
            while IFS=, read -r name url; do
              echo "#EXTINF:-1,${name}" >> local.m3u
              echo "${url}" >> local.m3u
            done < iptv.txt
          else
            echo "本地 iptv.txt 不存在，跳过"
          fi

      - name: Convert remote channels to m3u and merge
        run: |
          echo "#EXTM3U" > iptv.m3u
          echo "# Playlist Updated: $(date '+%Y-%m-%d %H:%M:%S')" >> iptv.m3u

          # 远程频道
          while IFS=, read -r name url; do
            echo "#EXTINF:-1,${name}" >> iptv.m3u
            echo "${url}" >> iptv.m3u
          done < clean.txt

          # 本地频道
          if [ -f local.m3u ]; then
            tail -n +2 local.m3u >> iptv.m3u
          fi

      - name: Commit and Push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          if [ -n "$(git status --porcelain iptv.m3u)" ]; then
            git add iptv.m3u
            git commit -m "Update IPTV playlist [$(date '+%Y-%m-%d %H:%M:%S')]"
            git push
          else
            echo "No changes detected, skip commit."
          fi
